on: push
     
jobs:
  opentofu_test:
    name: "Run OpenTofu tests"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::111111111111:role/lambda-sample-tests
          role-session-name: tests-${{ github.run_number }}-${{ github.actor }}
          aws-region: eu-west-3

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1    

      - name: Delete previous Terraform cache 
        run: |
          rm -rf .terraform .terraform.lock.hcl || true

      - name: Force reconfigure Terraform  
        env:
          TF_VAR_name: lambda-sample-${{ github.run_id }}
        working-directory: td5/scripts/tofu/live/lambda-sample
        run: |
          tofu init -reconfigure -backend=false -input=false
          tofu get
          tofu test -verbose

    